source: /exampleSite/
paths:
  uploads: static/uploads
  static: static
collections_config:
  pages:
    path: content
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  authors:
    path: content/authors
    glob:
      - '!_index.md'
    icon: person
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs:
    path: content/docs
    glob:
      - '!_index.md'
    icon: docs
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  examples:
    path: content/examples
    glob:
      - '!_index.md'
    icon: enable
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  guides:
    path: content/guides
    glob:
      - '!_index.md'
    icon: files
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  samples:
    path: content/samples
    glob:
      - '!_index.md'
    icon: ripples
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  tags:
    path: content/tags
    glob:
      - '!_index.md'
    icon: tabs
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    icon: data_usage
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
